plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 10
paginate_path: "page/:num"
baseurl: ""



defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "TripleBrain"
email: 7418040@ed.tus.ac.jp
description: "学科の同期3人のブログ"
github:
  username: AriNie
swiftype:
  searchId: 
gitment:
    repo: blog
    client_id: 
    client_secret: 

# url: "https://arinie.github.io/TripleBrain"
# imgrepo: "https://arinie.github.io/TripleBrain/static/img"


url: "http://127.0.0.1:4000"
imgrepo: "http://127.0.0.1:4000/static/img"

# url: "http://127.0.0.1:80"
# imgrepo: "http://127.0.0.1:80/static/img"


